// Simple PDF-like document generator using HTML and CSS
// This is a fallback for when @react-pdf/renderer has native binding issues

import { K4ViewLogoBase64 } from "../../assets/k4viewLogo";

export interface UserCredentialsData {
  displayName: string;
  generatedEmail: string;
  tempPassword: string;
}

export const generateUserCredentialsHTML = (user: UserCredentialsData): string => {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>K4View User Credentials</title>
      <style>
        @page {
          size: A4;
          margin: 0;
        }
        
        body {
          font-family: 'Helvetica', Arial, sans-serif;
          line-height: 1.6;
          color: #ffffff;
          background-color: #2c5f7c;
          margin: 0;
          padding: 40px;
          min-height: 100vh;
          box-sizing: border-box;
        }
        
        .container {
          max-width: 100%;
          margin: 0;
          background: #2c5f7c;
          padding: 0;
          min-height: calc(100vh - 80px);
          position: relative;
        }
        
        .header {
          display: flex;
          align-items: center;
          border-bottom: 2px solid #4a8db8;
          padding-bottom: 20px;
          margin-bottom: 60px;
        }
        
        .logo-image {
          width: 73px;
          height: 22px;
          margin-right: 15px;
        }
        
        .logo-text {
          font-size: 28px;
          font-weight: bold;
          color: #ffffff;
          letter-spacing: 1px;
        }
        
        .subtitle {
          font-size: 12px;
          color: #ffffff;
          margin-left: 15px;
          opacity: 0.8;
          font-weight: normal;
        }
        
        .title {
          font-size: 18px;
          font-weight: normal;
          font-style: italic;
          color: #ffffff;
          margin: 40px 0 40px 0;
        }
        
        .credentials-container {
          margin: 30px 0;
        }
        
        .credential-row {
          display: flex;
          align-items: center;
          margin-bottom: 25px;
        }
        
        .label {
          font-size: 14px;
          color: #ffffff;
          width: 120px;
          opacity: 0.9;
        }
        
        .value {
          font-size: 14px;
          color: #ffffff;
          font-weight: bold;
          margin-left: 80px;
        }
        
        .footer {
          position: absolute;
          bottom: 30px;
          left: 40px;
          right: 40px;
          text-align: center;
          color: #ffffff;
          font-size: 10px;
          opacity: 0.7;
        }
        
        @media print {
          body {
            background-color: #2c5f7c;
            -webkit-print-color-adjust: exact;
            color-adjust: exact;
          }
          
          .container {
            margin: 0;
            padding: 0;
            min-height: 100vh;
          }
        }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <img src="${K4ViewLogoBase64}" alt="K4View Logo" class="logo-image" />
          <div>
            <div class="logo-text">K4VIEW</div>
            <div class="subtitle">ENERGY MARKET INSIGHT</div>
          </div>
        </div>
        
        <div class="title">Security Information:</div>
        
        <div class="credentials-container">
          <div class="credential-row">
            <div class="label">Display Name</div>
            <div class="value">${user.displayName}</div>
          </div>
          <div class="credential-row">
            <div class="label">User Name</div>
            <div class="value">${user.generatedEmail}</div>
          </div>
          <div class="credential-row">
            <div class="label">Temp Password</div>
            <div class="value">${user.tempPassword}</div>
          </div>
        </div>
        
        <div class="footer">
          Generated by K4View Admin • ${new Date().toLocaleDateString()} • Confidential Document
        </div>
      </div>
    </body>
    </html>
  `;
};

export const openPrintableCredentials = (user: UserCredentialsData) => {
  const htmlContent = generateUserCredentialsHTML(user);
  const blob = new Blob([htmlContent], { type: "text/html" });
  const url = URL.createObjectURL(blob);

  const printWindow = window.open(url, "_blank");

  if (printWindow) {
    // Wait for content to load then focus for printing
    printWindow.onload = () => {
      printWindow.focus();
      printWindow.print();
    };

    // Clean up the object URL after a delay
    setTimeout(() => {
      URL.revokeObjectURL(url);
    }, 2000);
  }
};

export const downloadCredentialsHTML = (user: UserCredentialsData) => {
  const htmlContent = generateUserCredentialsHTML(user);
  const blob = new Blob([htmlContent], { type: "text/html" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = `${user.generatedEmail}-credentials.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
};
