import { Document, Page, Text, View, StyleSheet, Font, Image } from "@react-pdf/renderer";

import { K4ViewLogoBase64 } from "../../assets/k4viewLogo";


const PDFColors = {
  Background: "#2c5f7c",
  TextTitle: "#ffffff",
  TextNormal: "#ffffff",
  Lines: "#4a8db8",
  Primary: "#ffffff", 
  LabelBackground: "rgba(255, 255, 255, 0.1)", 
};

Font.register({
  family: "Helvetica",
  fonts: [
    { src: "Helvetica" },
    { src: "Helvetica-Bold", fontWeight: "bold" },
    { src: "Helvetica-Oblique", fontStyle: "italic" },
    { src: "Helvetica-BoldOblique", fontWeight: "bold", fontStyle: "italic" },
  ],
});

const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: PDFColors.Background,
    padding: 40,
    fontFamily: "Helvetica",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 40,
    borderBottomWidth: 2,
    borderBottomColor: PDFColors.Lines,
    paddingBottom: 20,
  },
  logoImage: {
    width: 73,
    height: 22,
    marginRight: 15,
  },
  logoText: {
    fontSize: 28,
    fontWeight: "bold",
    color: PDFColors.Primary,
    letterSpacing: 1,
  },
  subtitle: {
    fontSize: 12,
    color: PDFColors.TextNormal,
    marginLeft: 10,
    opacity: 0.8,
  },
  title: {
    fontSize: 18,
    fontWeight: "normal",
    fontStyle: "italic",
    color: PDFColors.TextTitle,
    marginBottom: 40,
    marginTop: 40,
  },
  credentialsContainer: {
    marginTop: 30,
  },
  credentialRow: {
    flexDirection: "row",
    marginBottom: 25,
    alignItems: "center",
  },
  label: {
    fontSize: 14,
    color: PDFColors.TextNormal,
    width: 120,
    opacity: 0.9,
  },
  value: {
    fontSize: 14,
    color: PDFColors.TextNormal,
    fontWeight: "bold",
    marginLeft: 80,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    color: PDFColors.TextNormal,
    fontSize: 10,
    opacity: 0.7,
  },
});

interface UserCredentialsPDFProps {
  user: {
    displayName: string;
    generatedEmail: string;
    tempPassword: string;
  };
}

export const UserCredentialsPDF = ({ user }: UserCredentialsPDFProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Image style={styles.logoImage} src={K4ViewLogoBase64} />
        <View>
          <Text style={styles.logoText}>K4VIEW</Text>
          <Text style={styles.subtitle}>ENERGY MARKET INSIGHT</Text>
        </View>
      </View>

      {/* Title */}
      <Text style={styles.title}>Security Information:</Text>

      {/* Credentials */}
      <View style={styles.credentialsContainer}>
        <View style={styles.credentialRow}>
          <Text style={styles.label}>Display Name</Text>
          <Text style={styles.value}>{user.displayName}</Text>
        </View>
        <View style={styles.credentialRow}>
          <Text style={styles.label}>User Name</Text>
          <Text style={styles.value}>{user.generatedEmail}</Text>
        </View>
        <View style={styles.credentialRow}>
          <Text style={styles.label}>Temp Password</Text>
          <Text style={styles.value}>{user.tempPassword}</Text>
        </View>
      </View>

      {/* Footer */}
      <Text style={styles.footer}>
        Generated by K4View Admin • {new Date().toLocaleDateString()} • Confidential Document
      </Text>
    </Page>
  </Document>
);
