name: "Dependency Review"
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Dependency Review"
        uses: actions/dependency-review-action@bf0431a34222d43b6fa4afd81f80381020d83cf4 # Version 4.3.3 # https://github.com/actions/dependency-review-action/releases/tag/v4.3.3
        with:
          # Use comma-separated names to pass list arguments:
          allow-licenses: MIT,Apache-2.0,BSD-3-Clause,CC0-1.0,BSD-2-Clause,ISC,Python-2.0,MPL-2.0,0BSD,Unlicense,CC-BY-3.0,CC-BY-4.0,BSD-3-Clause-Clear,OFL-1.1,Zlib,ISC AND MIT
